/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace AnnouncementLog {
  export type AnnouncementStruct = {
    contentHash: BytesLike;
    group: BytesLike;
    category: string;
    timestamp: BigNumberish;
    publisher: AddressLike;
  };

  export type AnnouncementStructOutput = [
    contentHash: string,
    group: string,
    category: string,
    timestamp: bigint,
    publisher: string
  ] & {
    contentHash: string;
    group: string;
    category: string;
    timestamp: bigint;
    publisher: string;
  };
}

export interface AnnouncementLogInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "count"
      | "get"
      | "getAll"
      | "getPage"
      | "publish"
      | "roleManager"
      | "verify"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "AnnouncementPublished"): EventFragment;

  encodeFunctionData(functionFragment: "count", values?: undefined): string;
  encodeFunctionData(functionFragment: "get", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "getAll", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getPage",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "publish",
    values: [BytesLike, BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "roleManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "verify",
    values: [BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "count", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "get", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getAll", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getPage", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "publish", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "roleManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verify", data: BytesLike): Result;
}

export namespace AnnouncementPublishedEvent {
  export type InputTuple = [
    id: BigNumberish,
    contentHash: BytesLike,
    group: BytesLike,
    category: string,
    publisher: AddressLike
  ];
  export type OutputTuple = [
    id: bigint,
    contentHash: string,
    group: string,
    category: string,
    publisher: string
  ];
  export interface OutputObject {
    id: bigint;
    contentHash: string;
    group: string;
    category: string;
    publisher: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AnnouncementLog extends BaseContract {
  connect(runner?: ContractRunner | null): AnnouncementLog;
  waitForDeployment(): Promise<this>;

  interface: AnnouncementLogInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  count: TypedContractMethod<[], [bigint], "view">;

  get: TypedContractMethod<
    [id: BigNumberish],
    [AnnouncementLog.AnnouncementStructOutput],
    "view"
  >;

  getAll: TypedContractMethod<
    [],
    [AnnouncementLog.AnnouncementStructOutput[]],
    "view"
  >;

  getPage: TypedContractMethod<
    [offset: BigNumberish, limit: BigNumberish],
    [AnnouncementLog.AnnouncementStructOutput[]],
    "view"
  >;

  publish: TypedContractMethod<
    [contentHash: BytesLike, group: BytesLike, category: string],
    [void],
    "nonpayable"
  >;

  roleManager: TypedContractMethod<[], [string], "view">;

  verify: TypedContractMethod<
    [id: BigNumberish, hash: BytesLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "count"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "get"
  ): TypedContractMethod<
    [id: BigNumberish],
    [AnnouncementLog.AnnouncementStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAll"
  ): TypedContractMethod<
    [],
    [AnnouncementLog.AnnouncementStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPage"
  ): TypedContractMethod<
    [offset: BigNumberish, limit: BigNumberish],
    [AnnouncementLog.AnnouncementStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "publish"
  ): TypedContractMethod<
    [contentHash: BytesLike, group: BytesLike, category: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "roleManager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "verify"
  ): TypedContractMethod<
    [id: BigNumberish, hash: BytesLike],
    [boolean],
    "view"
  >;

  getEvent(
    key: "AnnouncementPublished"
  ): TypedContractEvent<
    AnnouncementPublishedEvent.InputTuple,
    AnnouncementPublishedEvent.OutputTuple,
    AnnouncementPublishedEvent.OutputObject
  >;

  filters: {
    "AnnouncementPublished(uint256,bytes32,bytes32,string,address)": TypedContractEvent<
      AnnouncementPublishedEvent.InputTuple,
      AnnouncementPublishedEvent.OutputTuple,
      AnnouncementPublishedEvent.OutputObject
    >;
    AnnouncementPublished: TypedContractEvent<
      AnnouncementPublishedEvent.InputTuple,
      AnnouncementPublishedEvent.OutputTuple,
      AnnouncementPublishedEvent.OutputObject
    >;
  };
}
