/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AcknowledgmentLog } from "./AcknowledgmentLog";
export type { AnnouncementLog } from "./AnnouncementLog";
export type { DocumentRegistry } from "./DocumentRegistry";
export type { RoleManager } from "./RoleManager";
