/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AcknowledgmentLog__factory } from "./AcknowledgmentLog__factory";
export { AnnouncementLog__factory } from "./AnnouncementLog__factory";
export { DocumentRegistry__factory } from "./DocumentRegistry__factory";
export { RoleManager__factory } from "./RoleManager__factory";
